version: '3'
services:
  # add the mariadb service
  db:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 8080:8080
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}

  
  # Optional GUI for mariadb
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

# To use the CLI to access mariadb directly execute the following:
# docker exec -it mariadb mysql --user=root --password=password

# Login details for the mariadb GUI localhost:8080:
# Server = name of the mariadb container. "mariadb" in my case.
# Username = root
# Password = password (same as the password mentioned above)